drop table IF EXISTS Employee;
create TABLE Employee (
  ID         BIGINT         NOT NULL AUTO_INCREMENT,
  DEPARTMENT       VARCHAR(255) NOT NULL,
  EMPLOYEE_NAME VARCHAR(255) NOT NULL,
  EMPLOYEE_SALARY  INT(10) NOT NULL,
  PRIMARY KEY (ID)
);